scr_initenemy();
usepalette = true;
is_controllable = true;
landspr = spr_slimebounce;
idlespr = spr_slimeidle;
fallspr = spr_slimefall;
stunfallspr = spr_slimestun;
walkspr = spr_slimemove;
turnspr = spr_slimeturn;
recoveryspr = spr_slimerecovery;
grabbedspr = spr_slimegrabbed;
scaredspr = spr_slime_scared;
ragespr = spr_cheeseslime_rage;
image_xscale = -1;
spr_dead = spr_slimedead;
spr_palette = palette_cheeseslime;
sprite_index = spr_slimemove;
snotty = false;
