enum states
{
	normal = 0,
	revolver = 1,
	dynamite = 2,
	boots = 3,
	grabbed = 4,
	tumble = 5,
	finishingblow = 6,
	ejected = 7,
	transitioncutscene = 8,
	fireass = 9,
	firemouth = 10,
	mort = 11,
	mortjump = 12,
	mortattack = 13,
	morthook = 14,
	hook = 15,
	ghost = 16,
	ghostpossess = 17,
	titlescreen = 18,
	hookshot = 19,
	tacklecharge = 20,
	cheeseball = 21,
	cheeseballclimbwall = 22,
	slap = 23,
	cheesepep = 24,
	cheesepepstick = 25,
	cheesepepjump = 26,
	cheesepepfling = 27,
	cheesepeplaunch = 28,
	cheesepepstickside = 29,
	cheesepepstickup = 30,
	rideweenie = 31,
	motorcycle = 32,
	boxxedpep = 33,
	boxxedpepspin = 34,
	boxxedpepjump = 35,
	pistolaim = 36,
	climbwall = 37,
	knightpepslopes = 38,
	portal = 39,
	secondjump = 40,
	chainsawbump = 41,
	handstandjump = 42,
	lungeattack = 43,
	lungegrab = 44,
	dashtumble = 45,
	gottreasure = 46,
	knightpep = 47,
	knightpepattack = 48,
	knightpepbump = 49,
	meteorpep = 50,
	bombpep = 51,
	bombgrab = 52,
	bombpepside = 53,
	bombpepup = 54,
	grabbing = 55,
	chainsawpogo = 56,
	shotgunjump = 57,
	pogo = 58,
	stunned = 59,
	highjump = 60,
	chainsaw = 61,
	facestomp = 62,
	mach4 = 63, // doesnt exist
	timesup = 64,
	machroll = 65,
	shotgun = 66,
	shotguncrouch = 67,
	shotguncrouchjump = 68,
	shotgunshoot = 69,
	shotgundash = 70,
	shotgunfreefall = 71,
	pistol = 72,
	machfreefall = 73,
	throwing = 74,
	slam = 75,
	superslam = 76,
	skateboard = 77,
	grind = 78,
	grab = 79,
	punch = 80,
	backkick = 81,
	uppunch = 82,
	shoulder = 83,
	backbreaker = 84,
	graffiti = 85,
	bossdefeat = 86,
	pizzathrow = 87,
	bossintro = 88,
	gameover = 89,
	keyget = 90,
	tackle = 91,
	jump = 92,
	ladder = 93,
	slipnslide = 94,
	comingoutdoor = 95,
	smirk = 96,
	Sjump = 97,
	victory = 98,
	Sjumpprep = 99,
	crouch = 100,
	crouchjump = 101,
	crouchslide = 102,
	mach1 = 103,
	mach2 = 104,
	machslide = 105,
	bump = 106,
	hurt = 107,
	freefall = 108,
	hang = 109,
	unknown110 = 110, // turning, doesnt exist
	freefallland = 111,
	door = 112,
	barrel = 113,
	barreljump = 114,
	barrelclimbwall = 115,
	barrelslide = 116,
	current = 117,
	boulder = 118,
	taxi = 119,
	runonball = 120,
	mach3 = 121,
	freefallprep = 122,
	Sjumpland = 123,
	faceplant = 124,
	rage = 125,
	idle = 126,
	bounce = 127,
	charge = 128,
	pizzagoblinthrow = 129,
	turn = 130,
	unknown131 = 131, // hitceiling, doesnt exist
	unknown132 = 132, // hitwall, doesnt exist
	rolling = 133, // groundpoundland
	walk = 134,
	fall = 135,
	land = 136,
	hit = 137,
	stun = 138,
	unknown139 = 139, // recovery, doesnt exist
	unknown140 = 140, // stomped, doesnt exist
	chase = 141,
	arenaspawn = 142, // spawnenemy
	arenaend = 143,
	arenaintro = 144,
	arenaround = 145,
	actor = 146,
	parry = 147,
	golf = 148,
	float = 149,
	tube = 150,
	unknown151 = 151,
	taxi2 = 152, // policetaxi
	shoulderbash = 153,
	pummel = 154,
	staggered = 155,
	thrown = 156,
	supershoulderbash = 157,
	superattackstart = 158,
	superattackcharge = 159,
	superattack = 160,
	shoulderturn = 161,
	fistmatch = 162,
	fistmatchend = 163,
	groundpunchstart = 164,
	slipbanan = 165,
	millionpunch = 166,
	skateboardturn = 167,
	bombthrow = 168,
	bombpogo = 169,
	jetpackstart = 170,
	jetpack = 171,
	jetpackstart2 = 172,
	jetpackspin = 173,
	mrstick_shield = 174,
	mrstick_helicopterhat = 175,
	mrstick_panicjump = 176,
	mrstick_smokebombstart = 177,
	mrstick_smokebombcrawl = 178,
	mrstick_springshoes = 179,
	mrstick_cardboard = 180,
	mrstick_cardboardend = 181,
	mrstick_mockery = 182,
	bombdelete = 183,
	rocket = 184,
	rocketslide = 185,
	gotoplayer = 186,
	trickjump = 187,
	dance = 188,
	underground = 189,
	ridecow = 190,
	ratmount = 191,
	ratmountjump = 192,
	ratmountattack = 193,
	ratmountspit = 194,
	ratmountclimbwall = 195,
	ratmounthurt = 196,
	ratmountgroundpound = 197,
	ratmountbounce = 198,
	unknown199 = 199,
	ratmountballoon = 200,
	ratmounttumble = 201,
	ratmountgrind = 202,
	ratmounttrickjump = 203,
	ratmountskid = 204,
	ratgrabbed = 205,
	blockstance = 206,
	balloon = 207,
	debugstate = 208,
	trashstart = 209, // trashjumpprep
	trashjump = 210,
	trashroll = 211,
	stringfling = 212,
	stringjump = 213,
	stringfall = 214,
	noisejetpack = 215,
	spiderweb = 216,

	// robot states start
	monsteridle = 217,
	monsterintro = 218,
	monsterwalk = 219, // roaming
	monsterchase = 220,
	monsterinvestigate = 221,
	monsterrun = 222, // seeking
	// robot states end

	flushidle = 223,
	flushflip = 224, // flushtransition
	animatronic = 225,

	// pizzaface states start
	moustache = 226,
	mouth = 227,
	eyes = 228,
	nose = 229,
	ram = 230,
	phase2transition = 231,
	look = 232,
	fishing = 233,
	unknown234 = 234,
	bombrun = 235,
	npcthrow = 236,
	portraitthrow = 237,
	enguarde = 238,
	sexypicture = 239,
	pullinglevel = 240,
	eat = 241,
	surprisebox = 242,
	spinningrun = 243,
	spin = 244, // spinningkick
	spinningpunch = 245,
	groundpunch = 246,
	bigkick = 247,
	slamhead = 248,
	slamhead2 = 249,
	// pizzaface states end

	whitenoise = 250, // tv
	expression = 251, // tv
	playersuperattack = 252,
	unknown253 = 253,
	jetpackjump = 254,
	unknown255 = 255,
	unknown256 = 256,
	bee = 257,
	beechase = 258,
	ratmountpunch = 259,
	ratmountcrouch = 260,
	ratmountladder = 261,
	supergrab = 262,
	unknown263 = 263,
	attract = 264,
	antigrav = 265,
	secret = 266,
	contemplate = 267,
	mini = 268,
	reloading = 269,
	estampede = 270,
	dropstart = 271,
	drop = 272,
	phase1hurt = 273,
	duel = 274,
	deformed = 275,
	grabdash = 276,
	grabthrow = 277,
	wait = 278,
	flamethrower = 279,
	machinegun = 280,
	bazooka = 281,
	crate = 282,
	noisecrusher = 283,
	droptrap = 284,
	noiseskateboard = 285,
	noiseballooncrash = 286,
	swinging = 287,
	stomp = 288,
	finale = 289, // ending
	backtohub = 290,
	ghostcaught = 291, // johnghost
	spaceshuttle = 292,
	animation = 293,
	pizzaheadjump = 294,
	fightball = 295,
	secretportal = 296, // secretenter
	teleporter = 297, // teleport
	pizzaheadKO = 298,
	follow = 299, // camera_followtarget
	unknown300 = 300, // Mr. Stick wallkick
	unknown301 = 301, // Mr. Stick airspin
	unknown302 = 302, // Mr. Stick superjump
	unknown303 = 303, // Mr. Stick flycancel, used in obj_stickhat
	unknown304 = 304, // Mr. Stick flight
	machcancelstart = 305,
	machcancel = 306,
}

#macro ANIMATION_END floor(image_index) == (image_number - 1)

global.currentsavefile = 1;
var achievement_arr = ["sranks1", "sranks2", "sranks3", "sranks4", "sranks5"];
var data_arr = [get_save_folder() + "/saveData1", get_save_folder() + "/saveData2", get_save_folder() + "/saveData3"];
global.stickreq[0] = 100;
global.stickreq[1] = 150;
global.stickreq[2] = 200;
global.stickreq[3] = 200;
global.stickreq[4] = 210;
global.levelattempts = 0;
global.palette_arr = [false, false, false, false, false];
for (var i = 0; i < array_length(data_arr); i++)
{
	global.game[i] = scr_read_game(data_arr[i] + ".ini");
	global.gameN[i] = scr_read_game(data_arr[i] + "N.ini");
}
global.newtoppin[0] = false;
global.newtoppin[1] = false;
global.newtoppin[2] = false;
global.newtoppin[3] = false;
global.newtoppin[4] = false;
global.mach_color1 = make_colour_rgb(96, 208, 72);
global.mach_color2 = make_colour_rgb(248, 0, 0);
global.afterimage_color1 = make_colour_rgb(255, 0, 0);
global.afterimage_color2 = make_colour_rgb(0, 255, 0);
global.smallnumber_color1 = make_colour_rgb(255, 255, 255);
global.smallnumber_color2 = make_colour_rgb(248, 0, 0);
global.optimize = 0;
global.autotile = true;
global.smallnumber_fnt = font_add_sprite_ext(spr_smallnumber, "1234567890-+", true, 0);
global.pigreduction = 0;
global.pigtotal = 0;
global.levelcomplete = false;
global.levelcompletename = noone;
global.entrancetreasure = false;
global.medievaltreasure = false;
global.ruintreasure = false;
global.dungeontreasure = false;
global.deserttreasure = false;
global.graveyardtreasure = false;
global.farmtreasure = false;
global.spacetreasure = false;
global.beachtreasure = false;
global.foresttreasure = false;
global.pinballtreasure = false;
global.golftreasure = false;
global.streettreasure = false;
global.sewertreasure = false;
global.factorytreasure = false;
global.freezertreasure = false;
global.chateautreasure = false;
global.mansiontreasure = false;
global.kidspartytreasure = false;
global.wartreasure = false;
global.entrancecutscene = noone;
global.medievalcutscene = noone;
global.ruincutscene = noone;
global.ruincutscene2 = noone;
global.ruincutscene3 = noone;
global.dungeoncutscene = noone;
global.peppermancutscene1 = noone;
global.peppermancutscene2 = noone;
global.chieftaincutscene = noone;
global.chieftaincutscene2 = noone;
global.desertcutscene = noone;
global.graveyardcutscene = noone;
global.spacecutscene = noone;
global.vigilantecutscene1 = noone;
global.vigilantecutscene2 = noone;
global.vigilantecutscene3 = noone;
global.farmcutscene = noone;
global.superpinballcutscene = noone;
global.pubcutscene = noone;
global.pinballcutscene = noone;
global.beercutscene = noone;
global.exitfeecutscene = noone;
global.forestcutscene = noone;
global.bottlecutscene = noone;
global.papercutscene = noone;
global.beachboatcutscene = noone;
global.beachcutscene = noone;
global.sewercutscene = noone;
global.burgercutscene = noone;
global.golfcutscene = noone;
global.anarchistcutscene1 = noone;
global.anarchistcutscene2 = noone;
global.factoryblock = noone;
global.streetcutscene = noone;
global.graffiticutscene = noone;
global.factorygraffiti = noone;
global.factorycutscene = noone;
global.hatcutscene1 = noone;
global.hatcutscene2 = noone;
global.hatcutscene3 = noone;
global.jetpackcutscene = noone;
global.noisecutscene1 = noone;
global.noisecutscene2 = noone;
global.freezercutscene = noone;
global.kidspartycutscene = noone;
global.gasolinecutscene = noone;
global.mansioncutscene = noone;
global.chateaucutscene = noone;
global.ghostsoldiercutscene = noone;
global.mrstickcutscene1 = noone;
global.mrstickcutscene2 = noone;
global.mrstickcutscene3 = noone;
global.chateauswap = noone;
global.warcutscene = noone;
pal_swap_init_system(shd_pal_swapper);
with (obj_player1)
{
	state = states.normal;
}
global.loadeditor = false;
if (global.longintro)
{
	global.longintro = false;
	room_goto(Longintro);
}
else
{
	room_goto(Mainmenu);
}
instance_destroy(obj_cutscene_handler);